### ISSUE TITLE
What is 'RichardSzalay.Helix.Publishing.Module' for?

### ISSUE THREAD

**Issue by hombreDelPez** [richardszalay/helix-publishing-pipeline#58]
Hi Richard

First of all, thank you very much for your work and this awesome project :)

I noticed that there are currently **two** NuGet packages available on www.nuget.org which are related to HPP:
- [RichardSzalay.Helix.Publishing.WebRoot](https://www.nuget.org/packages/RichardSzalay.Helix.Publishing.WebRoot/)
- [RichardSzalay.Helix.Publishing.Module](https://www.nuget.org/packages/RichardSzalay.Helix.Publishing.Module/)

The weird thing is that the second package (RichardSzalay.Helix.Publishing.Module) isn't mentioned anywhere, also not in your readme.

So my question is, is this package used for a special use case (and if yes, for what) or is it on www.nuget.org by mistake (duplicate of the other package)? I did a file comparison and the contents of the two packages are exactly the same...

Best regards,
Manuel

**Comment by richardszalay** [comment]
Hi Manuel,

Great question! Originally, the idea was that if you weren't publishing the "WebRoot" you could reference `Module` and it would exclude the Web.config. In practice, though, it's simple enough to skip it manually and it was confusing to have two packages so I stopped directing people to it.

The packages can have the same contents because `build/(PackageName).targets` is automatically imported by NuGet, so it was easier to simply include both "entry point" target files in both packages.

As part of 2.0, I will likely deprecate both packages and direct (via a build error) updaters to a new `RichardSzalay.Helix.Publishing` package.

**Comment by hombreDelPez** [comment]
Hi Richard

Thank you for your clarifications :)

Best regards,
Manuel
